server: # 为什么改变端口号无效？使用pom形式打包，会导致target中没有application.yml文件，所以无法修改端口号，需要在target\classes下添加application.yml
    port: 8081
#    address: localhost
#    port: ${port:8081}

spring:
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    application:
      name: api-passenger
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        password: Lz826826
